### PR TITLE
Adding in ability to generate reports from the API

### PR DESCRIPTION
**Pull request by timcrider**
Added functionality based on the Usage Report API: http://help.skytap.com/#API_Documentation.html#Usage_Report_Resource

I have tested create, check, and fetch. These endpoints do not work with the v2 API.

*Fixing lint errors

### CODE REVIEW

**Comment by bmancini55** [comment]
Good stuff!  

Any chance you want to take a stab at writing the unit tests for these new methods?

**Comment by timcrider** [comment]
I haven't written a ton of tests (I promise it's on my bucket list though). The usage setup is kind of tricky to test. You have to create a report, then check the report until it is ready, then hit a 3rd endpoint to grab the actual report.

I have working scripts I can base them off of, and I have looked at the Users test. Users is what I based my Usage off of. If you have any pointers to get me started, I can try to get some tests up and running.

Tim

**Comment by bmancini55** [comment]
Sounds good!  We have some network mock tests written for the other API calls that you can use as a basis.  Check out this file: https://github.com/fti-technology/node-skytap/blob/master/test/users.js 

For example this test...
```javascript
it('requests a list of users', function () {
  return nockspect(function (nock) {
    nock.get('/users').reply(200);
    return _.bind(skytap.users.list, skytap.users);
  });
});
```
This test is using a custom helper function we have called `nockspect`.  It uses the `nock` library to perform network request mocking and assertions.  Basically, it will intercept a http request and allow you to assert that that url/headers/params was called as expected.  The nockspect function checks both the callback passing style and promise based style of methods to ensure the API is compliant with both methods.

The usage for writing one of these tests is this:
```javascript

it('does something, function() {

  // call nockspect with a test function to perform
  return nockspect(function(nock) {

    // setup a network mock
    nock.get('/my-expected-url?with=params').reply(200);

    // create and return a function binding that will be executed
    return _.bind(skytap.area.myFunc, skytap.area, { args: 'to-pass-func' });

    /* 
    // which is the equivalent of using native binding
    return skytap.area.myFunc.bind(skytap.area, { args: 'to-pass-func' });

    // or creating a function expression
    return function() {
      skytap.area.myFunc({ arg: 'to-pass-func' });
    };
    */    
  });
});
```

If you run into any trouble let me know.

**Comment by timcrider** [comment]
I did a first pass for the create test and it's complaining about no matching nock request.

<pre><code>
var chai      = require('chai')
  , expect    = chai.expect
  , Skytap    = require('../lib/skytap')
  , nockspect = require('./util/nockspect')
  , _         = require('underscore');

describe('Skytap.usage', function () {
  var skytap = Skytap.init({ username: 'foo', token: 'bar' });

  describe('.create', function () {
    it('create a SkyTap usage report', function () {
      return nockspect(function (nock) {
        var param = {
          start_date: '2015/04/01 00:00:00 -0800'
          ,end_date: '2015/04/30 23:59:59 -0800'
          ,resource_type: 'svms'
          ,region: 'all'
          ,group_by: 'department'
          ,aggregate_by: 'day'
          ,results_format: 'csv'
          ,utc: 'true'
        };

        nock.post('/create', param).reply(200);
        return _.bind(skytap.usage.create, skytap.usage);
      });
    });
  });
});
</code></pre>

<pre><code>
Error:
  1) Skytap.usage .create requests a list of users:
     Error: Nock: No match for request POST https://cloud.skytap.com/reports {"results_format":"csv","resource_type":"svms","region":"all","group_by":"user","aggregate_by":"month"}
</code></pre>

I checked other post nocks (environments, ips, projects) and can't seem to figure out why it's not matching.

Any thoughts?

**Comment by timcrider** [comment]
Just to clear up any confusion. The error message was from an earlier run before I changed the test name. The latest run fails with the correct wording:

<pre><code>
1) Skytap.usage .create create a SkyTap usage report:
</code></pre>

**Comment by bmancini55** [comment]
You just need to pass nock the correct url, `/reports` instead of `/create` and make sure you bind the params so they get passed to the call.

Replace this code...
```
nock.post('/create', param).reply(200);
return _.bind(skytap.usage.create, skytap.usage);
```

with this...
```
nock.post('/reports', param).reply(200);
return _.bind(skytap.usage.create, skytap.usage, param);
```

**Comment by timcrider** [comment]
That did it, I'll get the other 2 documented. I have not worked with exports, do you want me to tear that out for now?

**Comment by bmancini55** [comment]
Awesome!

Yeah if you haven't used it / validated it, I'd pull it out.  It can always be added when it's needed.

**Comment by timcrider** [comment]
I removed export, and have the test working for check. However, fetch is now complaining about a mismatch. Once this is done I can resubmit the pull request will full test coverage.

Test Block:
<pre><code>
  describe('.fetch', function () {
    it('fetch a SkyTap usage report', function () {
      return nockspect(function (nock) {
        nock.get('/reports/fetch/').reply(200);
        return _.bind(skytap.usage.fetch, skytap.usage, {
          report_id: 123456
          ,extension: 'csv'
        });
      });
    });
  });
</code></pre>

Endpoint:
<pre><code>
/**
 * Fetch a report
 *
 * @param {Object} params
 * @config {Number} report_id
 * @config {String} extension
 * @callback {Function} next
 * @return {Promise}
 */
Usage.prototype.fetch = function get(params, next) {
  debug('get %j', params);

  var args = this.getArgs();
  args.url = 'https://cloud.skytap.com/reports/'+params.report_id+'.'+params.extension;
//  args.params = params;
  return rest.apiGet(args, next);
};
</code></pre>

Error:
<pre><code>
  1) Skytap.usage .fetch fetch a SkyTap usage report:
     Error: Nock: No match for request GET https://cloud.skytap.com/reports/123456.csv
</code></pre>

**Comment by timcrider** [comment]
To clarify, the endpoint that SkyTap generates for fetching the reports looks like:

https://cloud.skytap.com/reports/123456.csv

I tried to use the normal endpoint syntax, and that fails as well:

https://cloud.skytap.com/reports/:report_id.:extension

**Comment by bmancini55** [comment]
Changing the nock url to match the expected url should do the trick:

```
nock.get('/reports/123456.csv').reply(200);
```

**Comment by timcrider** [comment]
This should be ready for merge now.

Thanks for your help, I'll make sure I get tests in next time I push something.

**Comment by bmancini55** [comment]
Awesome, thanks for getting this into the lib!

**Comment by bmancini55** [comment]
The version has been bumped to 0.6.0.  Thanks!

**Pull request merged**
